version: 2
updates:
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
    commit-message:
      prefix: chore
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore
    groups:
      commitlint:
        patterns:
          - '@commitlint*'
      typescript-eslint:
        patterns:
          - '@typescript-eslint*'
