---
name: Setup Ansible
description: Setups latest Ansible and installs Ansible Galaxy dependencies

inputs:
  cache-path:
    description: Folder to download Ansible Galaxy dependencies
    default: .ansible

runs:
  using: composite
  steps:
    - name: Load Cached Ansible Galaxy dependencies
      uses: actions/cache@v4
      id: ansible-galaxy-cache
      with:
        path: ${{ inputs.cache-path }}
        key: ansible-galaxy-${{ hashFiles('requirements.yml') }}

    - name: Install Ansible Galaxy dependencies
      if: steps.ansible-galaxy-cache.outputs.cache-hit != 'true'
      run: ansible-galaxy install -r requirements.yml
      shell: bash

    - name: Display Ansible version
      run: ansible --version
      shell: bash

    - name: Display Ansible Lint version
      run: ansible-lint --version
      shell: bash

    - name: Display Ansible Galaxy version
      run: ansible-galaxy --version
      shell: bash
