name: Setup Ansible
description: Setups latest Ansible and installs Ansible Galaxy dependencies

runs:
  using: composite
  steps:
    - name: Load Cached Ansible Galaxy dependencies
      uses: actions/cache@v3
      id: ansible-galaxy-cache
      with:
        path: galaxy
        key: ansible-galaxy-${{ hashFiles('requirements.yml') }}

    - name: Display Ansible version
      run: ansible --version
      shell: bash

    - name: Display Ansible Galaxy version
      run: ansible-galaxy --version
      shell: bash

    - name: Install Ansible Galaxy dependencies
      run: ansible-galaxy install -r requirements.yml
      shell: bash

    - name: Save in Cache Ansible Galaxy dependencies
      uses: actions/cache@v3
      if: steps.ansible-galaxy-cache.outputs.cache-hit != 'true'
      with:
        path: galaxy
        key: ansible-galaxy-${{ hashFiles('requirements.yml') }}
