---
name: Setup Ansible
description: Setups latest Ansible and installs Ansible Galaxy dependencies

inputs:
  cache-path:
    description: Folder to download Ansible Galaxy dependencies
    default: .ansible
  working-directory:
    description: Action working directory
    default: .

runs:
  using: composite
  steps:
    - name: Load Cached Ansible Galaxy dependencies
      uses: actions/cache@v4
      id: ansible-galaxy-cache
      with:
        path: ${{ inputs.cache-path }}
        key: ansible-galaxy-${{ hashFiles('**/*requirements.yml') }}

    - name: Install Ansible Galaxy dependencies
      if: steps.ansible-galaxy-cache.outputs.cache-hit != 'true'
      run: ansible-galaxy install -r requirements.yml
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Display Ansible and tools versions
      run: |
        echo
        echo "🅰️ Ansible version: $(ansible --version)"
        echo "🅰️ Ansible Lint version: $(ansible-lint --version)"
        echo "🅰️ Ansible Galaxy: $(ansible-galaxy --version)"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
