---
name: Setup Ansible
description: Setups latest Ansible and installs Ansible Galaxy dependencies

inputs:
  cache-path:
    description: Folder to download Ansible Galaxy dependencies
    default: .ansible
  working-directory:
    description: Action working directory
    default: .

outputs:
  ansible-version:
    description: Installed Ansible version
    value: ${{ steps.display-installed-versions.outputs.ansible-version }}
  ansible-lint-version:
    description: Installed Ansible Lint version
    value: ${{ steps.display-installed-versions.outputs.ansible-lint-version }}
  ansible-galaxy-version:
    description: Installed Ansible Galaxy version
    value: ${{ steps.display-installed-versions.outputs.ansible-galaxy-version }}
  jobs-cache-key:
    description: Ansible jobs cache
    value: ${{ steps.calculate-cache-key.outputs.cache-key }}

runs:
  using: composite
  steps:
    - name: Calculate cache key
      id: calculate-cache-key
      run: |
        echo
        echo "🔑 Calculating cache key"
        CACHE_KEY="ansible-galaxy-jobs-${{ hashFiles(format('{0}/**/requirements.yml', inputs.working-directory)) }}"
        echo "🔑 Calculated cache key: $CACHE_KEY"
        echo "cache-key=$CACHE_KEY" >> "$GITHUB_OUTPUT"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Load Cached Ansible Galaxy dependencies
      uses: actions/cache@v4
      id: ansible-galaxy-cache
      with:
        path: ${{ inputs.working-directory }}/${{ inputs.cache-path }}
        key: ${{ steps.calculate-cache-key.outputs.cache-key }}

    - name: Install Ansible Galaxy dependencies
      if: steps.ansible-galaxy-cache.outputs.cache-hit != 'true'
      run: |
        echo
        echo "::group::🅰️ Installing Ansible Galaxy dependencies"
        ansible-galaxy install -r requirements.yml
        echo "::endgroup::"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Display Ansible and tools versions
      id: display-installed-versions
      run: |
        echo
        ANSIBLE_VERSION=$(ansible --version | sed -n '1s/.*core \([0-9.]*\).*/\1/p' | tr -d '\n')
        ANSIBLE_LINT_VERSION=$(ansible-lint --version --nocolor | sed -n '1s/^ansible-lint \([0-9.]*\).*/\1/p')
        ANSIBLE_GALAXY_VERSION=$(ansible-galaxy --version | sed -n '1s/.*core \([0-9.]*\).*/\1/p')

        echo "ansible-version=$ANSIBLE_VERSION" >> $GITHUB_OUTPUT
        echo "ansible-lint-version=$ANSIBLE_LINT_VERSION" >> $GITHUB_OUTPUT
        echo "ansible-galaxy-version=$ANSIBLE_GALAXY_VERSION" >> $GITHUB_OUTPUT

        echo "🅰️ Ansible version: $ANSIBLE_VERSION"
        echo "🅰️ Ansible Lint version: $ANSIBLE_LINT_VERSION"
        echo "🅰️ Ansible Galaxy: $ANSIBLE_GALAXY_VERSION"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Calculate dependencies size
      run: |
        echo
        echo "⚖️ Calculating dependencies size"
        du -sh ${{ inputs.cache-path }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
