---
name: Setup Ansible
description: Setups latest Ansible and installs Ansible Galaxy dependencies

inputs:
  cache-path:
    description: Folder to download Ansible Galaxy dependencies
    default: .ansible
  working-directory:
    description: Action working directory
    default: .

runs:
  using: composite
  steps:
    - name: Load Cached Ansible Galaxy dependencies
      uses: actions/cache@v4
      id: ansible-galaxy-cache
      with:
        path: ${{ inputs.cache-path }}
        key: ansible-galaxy-${{ hashFiles('**/*requirements.yml') }}

    - name: Install Ansible Galaxy dependencies
      if: steps.ansible-galaxy-cache.outputs.cache-hit != 'true'
      run: |
        echo
        echo "::group::🅰️ Installing Ansible Galaxy dependencies"
        ansible-galaxy install -r requirements.yml
        echo "::endgroup::"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Display Ansible and tools versions
      run: |
        echo
        ANSIBLE_VERSION=$(ansible --version | sed -n '1s/.*core \([0-9.]*\).*/\1/p' | tr -d '\n')
        ANSIBLE_LINT_VERSION=$(ansible-lint --version | sed -n '1s/^ansible-lint \x1b\[1;36m\([0-9.]*\).*/\1/p')
        ANSIBLE_GALAXY_VERSION=$(ansible-galaxy --version | sed -n '1s/.*core \([0-9.]*\).*/\1/p')

        echo "🅰️ Ansible version: $ANSIBLE_VERSION"
        echo "🅰️ Ansible Lint version: $ANSIBLE_LINT_VERSION"
        echo "🅰️ Ansible Galaxy: $ANSIBLE_GALAXY_VERSION"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
