---
name: Setup Node
description: Setups latest Node LTS and installs dependencies

inputs:
  node-version:
    description: Node version to install
    default: '24'
  working-directory:
    description: Action working directory
    default: .

outputs:
  node-version:
    description: Installed Node.js version
    value: ${{ steps.display-installed-versions.outputs.node-version }}
  package-manager:
    description: Node.js Package Manager
    value: ${{ steps.detect-node-pm.outputs.node-pm }}
  package-manager-version:
    description: Installed Node.js Package Manager version
    value: ${{ steps.display-installed-versions.outputs.package-manager-version }}
  cache-hit:
    description: A boolean value to indicate an exact match was found for the primary key
    value: ${{ steps.node-modules-cache.outputs.cache-hit }}
  global-cache-file:
    description: Node.js Package Manager global cache
    value: ${{ steps.output-cache-files.outputs.global-cache }}
  jobs-cache-file:
    description: Node.js Package Manager jobs cache
    value: ${{ steps.output-cache-files.outputs.jobs-cache }}

runs:
  using: composite
  steps:
    - name: Detect version to install
      id: detect-version-to-install
      run: |
        echo
        echo "📦 Detecting Node.js version"
        VERSION=$(cat .node-version 2>/dev/null || cat .nvmrc 2>/dev/null || echo "${{ inputs.node-version }}")
        VERSION=$(echo "$VERSION" | sed 's/^v//')
        echo "📦 Detected Node.js version: $VERSION"

        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Detect Node.js Package Manager
      id: detect-node-pm
      # Detect supported package managers by actions/setup-node
      # npm, pnpm, yarn1, yarn
      # https://github.com/actions/setup-node/blob/main/src/cache-utils.ts
      run: |
        echo
        echo "📦 Detecting Node.js Package Manager"
        CACHE_PATH=${{ inputs.working-directory }}/**/node_modules
        if [ -f "yarn.lock" ]; then
          if [ -d ".yarn" ] || [ -f ".yarnrc.yml" ]; then
            PM="yarn"
            CACHE_PATH="$CACHE_PATH$(echo -e "\n${{ inputs.working-directory }}/.yarn")"
          else
            PM="yarn1"
          fi
          CACHE="yarn"
          LOCK="yarn.lock"
        elif [ -f "pnpm-lock.yaml" ]; then
          PM="pnpm"
          CACHE="pnpm"
          LOCK="pnpm-lock.yaml"
        else
          PM="npm"
          CACHE="npm"
          LOCK="package-lock.json"
        fi

        echo "node-pm=$PM" >> "$GITHUB_OUTPUT"
        echo "node-cache=$CACHE" >> "$GITHUB_OUTPUT"
        echo "node-lock=$LOCK" >> "$GITHUB_OUTPUT"
        echo "cache-path<<EOF" >> "$GITHUB_OUTPUT"
        echo "$CACHE_PATH" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

        echo "📦 Detected Node.js Package Manager: $PM"
        echo "::debug::--- 📦 Node.js Package Manager ---"
        echo "::debug::Package Manager Name: $PM"
        echo "::debug::Package Manager Cache Type: $CACHE"
        echo "::debug::Package Manager Lock File: $LOCK"
        echo "::debug::Cache Paths:\n$CACHE_PATH"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Cache dependencies between jobs
      uses: actions/cache@v5
      id: node-modules-cache
      with:
        path: ${{ env.CACHE-PATH }}
        key: ${{ env.CACHE-PREFIX }}-${{ env.RUNNER_NAME }}-${{ env.PM }}-${{ hashFiles(env.HASHED) }}
      env:
        CACHE-PATH: ${{ steps.detect-node-pm.outputs.cache-path }}
        CACHE-PREFIX: setup-node-${{ steps.detect-version-to-install.outputs.version }}-internal
        HASHED: ${{ inputs.working-directory }}/${{ steps.detect-node-pm.outputs.node-lock }}
        PM: ${{ steps.detect-node-pm.outputs.node-pm }}
        RUNNER_NAME: ${{ runner.os }}-${{ runner.arch }}

    - name: Prepare Node.js
      if: ${{ env.PM != 'npm' && env.PM != 'yarn1' }}
      uses: actions/setup-node@v6
      with:
        check-latest: true
        node-version: ${{ steps.detect-version-to-install.outputs.version }}

    - name: Enable Corepack
      if: ${{ env.PM != 'npm' && env.PM != 'yarn1' }}
      run: |
        echo
        echo "🧰 Enabling Corepack for $PM"
        corepack enable

        PM_VERSION=$(node -pe "try{require('./package.json').packageManager}catch{}")
        [ -z "$PM_VERSION" ] && PM_VERSION="$PM@latest"

        echo "🧰 Preparing Corepack for $PM_VERSION"
        corepack prepare "$PM_VERSION" --activate
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        PM: ${{ steps.detect-node-pm.outputs.node-pm }}

    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        # Reference for setup-node action options
        # https://github.com/actions/setup-node/blob/main/action.yml
        # https://github.com/actions/setup-node#usage
        cache: ${{ (env.CACHE-HIT != 'true' && env.CACHE) || '' }}
        cache-dependency-path: ${{ inputs.working-directory }}/${{ env.LOCK }}
        check-latest: true
        node-version: ${{ steps.detect-version-to-install.outputs.version }}
      env:
        LOCK: ${{ steps.detect-node-pm.outputs.node-lock }}
        CACHE: ${{ steps.detect-node-pm.outputs.node-cache }}
        CACHE-HIT: ${{ steps.node-modules-cache.outputs.cache-hit }}

    - name: Display installed Node.js and Package Manager versions
      id: display-installed-versions
      run: |
        echo
        NODE_VERSION=$(node -v | sed 's/^v//')
        PM_VERSION=$(
          case "$PM" in
            yarn1|yarn) yarn -v ;;
            pnpm) pnpm -v ;;
            *) npm -v ;;
          esac
        )
        echo "node-version=$NODE_VERSION" >> $GITHUB_OUTPUT
        echo "package-manager-version=$PM_VERSION" >> $GITHUB_OUTPUT
        echo "📦 Node.js version: $NODE_VERSION"
        echo "📦 $PM version: $PM_VERSION"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        PM: ${{ steps.detect-node-pm.outputs.node-pm }}

    - name: Output cache files
      id: output-cache-files
      run: |
        echo
        OS=${{ runner.os }}
        ARCH=${{ runner.arch }}
        ARCH_LOWER="$(echo "$ARCH" | tr '[:upper:]' '[:lower:]')"
        PM=${{ steps.detect-node-pm.outputs.node-pm }}
        PM_CACHE=${{ steps.detect-node-pm.outputs.node-cache }}
        NODE_VERSION=${{ steps.detect-version-to-install.outputs.version }}

        GLOBAL_CACHE=node-cache-$OS-$ARCH_LOWER-$PM_CACHE-$CACHE_HASH
        JOBS_CACHE=setup-node-$NODE_VERSION-internal-$OS-$ARCH-$PM-$CACHE_HASH

        echo "💾 Global cache file: $GLOBAL_CACHE"
        echo "💾 Jobs cache file: $JOBS_CACHE"

        echo "global-cache=$GLOBAL_CACHE" >> "$GITHUB_OUTPUT"
        echo "jobs-cache=$JOBS_CACHE" >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        CACHE_HASH: ${{ hashFiles(format('{0}/{1}', inputs.working-directory, steps.detect-node-pm.outputs.node-lock))}}

    - name: Install Dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: |
        echo
        echo "::group::📦 Installing dependencies"
        case "$PM" in
          yarn1) yarn install --frozen-lockfile ;;
          yarn) yarn --immutable ;;
          pnpm) pnpm install --frozen-lockfile ;;
          *) npm ci ;;
        esac
        echo "::endgroup::"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        PM: ${{ steps.detect-node-pm.outputs.node-pm }}

    - name: Calculate dependencies size
      run: |
        echo
        echo "⚖️ Calculating dependencies size"

        find . -path "*/node_modules" -type d -prune -print | \
        xargs -r du -sm | \
        sort -nr | \
        while read -r size path; do
          printf "\033[1;35m %4sM \033[0m %s\n" "$size" "$path"
        done
      shell: bash
      working-directory: ${{ inputs.working-directory }}
