name: Setup Node
description: Setups latest Node LTS and installs dependencies

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        # Reference for setup-node action options
        # https://github.com/actions/setup-node/blob/main/action.yml
        # https://github.com/actions/setup-node#usage
        cache: npm
        check-latest: true
        node-version: 18
    - name: Install Dependencies
      run: npm ci
      shell: bash
