---
name: Setup Node
description: Setups latest Node LTS and installs dependencies

inputs:
  node-version:
    description: Node version to install
    default: '22'
  working-directory:
    description: Action working directory
    default: .

runs:
  using: composite
  steps:
    - name: Detect Node.js Package Manager
      id: detect-node-pm
      # Detect supported package managers by actions/setup-node
      # npm, pnpm, yarn1, yarn
      # https://github.com/actions/setup-node/blob/main/src/cache-utils.ts
      run: |
        echo
        CACHE_PATH=${{ inputs.working-directory }}/node_modules
        if [ -f "yarn.lock" ]; then
          if [ -d ".yarn" ] || [ -f ".yarnrc.yml" ]; then
            PM="yarn"
            CACHE_PATH="$CACHE_PATH\n${{ inputs.working-directory }}/.yarn"
          else
            PM="yarn1"
          fi
          CACHE="yarn"
          LOCK="yarn.lock"
        elif [ -f "pnpm-lock.yaml" ]; then
          PM="pnpm"
          CACHE="pnpm"
          LOCK="pnpm-lock.yaml"
        else
          PM="npm"
          CACHE="npm"
          LOCK="package-lock.json"
        fi

        echo "node-pm=$PM" >> "$GITHUB_OUTPUT"
        echo "node-cache=$CACHE" >> "$GITHUB_OUTPUT"
        echo "node-lock=$LOCK" >> "$GITHUB_OUTPUT"
        echo "cache-path<<EOF" >> "$GITHUB_OUTPUT"
        echo -e "$CACHE_PATH" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

        echo "::debug::--- 📦 Node.js Package Manager ---"
        echo "::debug::Package Manager Name: $PM"
        echo "::debug::Package Manager Cache Type: $CACHE"
        echo "::debug::Package Manager Lock File: $LOCK"
        echo "::debug::Cache Paths:\n$CACHE_PATH"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Load Cached Package Manager dependencies
      uses: actions/cache@v4
      id: node-modules-cache
      with:
        path: ${{ env.CACHE-PATH }}
        key: ${{ env.CACHE-PREFIX }}-${{ env.PM }}-${{ hashFiles(env.HASHED) }}
      env:
        CACHE-PATH: ${{ steps.detect-node-pm.outputs.cache-path }}
        CACHE-PREFIX: setup-node-${{ inputs.node-version }}-internal-${{ runner.os }}-${{ runner.arch }}
        HASHED: ${{ inputs.working-directory }}/${{ steps.detect-node-pm.outputs.node-lock }}
        PM: ${{ steps.detect-node-pm.outputs.node-pm }}

    - name: Enable Corepack
      run: |
        if [ $PM != "npm" ]; then
          corepack enable
        fi
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        PM: ${{ steps.detect-node-pm.outputs.node-pm }}

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        # Reference for setup-node action options
        # https://github.com/actions/setup-node/blob/main/action.yml
        # https://github.com/actions/setup-node#usage
        cache: ${{ (env.CACHE-HIT != 'true' && env.CACHE) || '' }}
        cache-dependency-path: ${{ inputs.working-directory }}/${{ env.LOCK }}
        check-latest: true
        node-version: ${{ inputs.node-version }}
      env:
        LOCK: ${{ steps.detect-node-pm.outputs.node-lock }}
        CACHE: ${{ steps.detect-node-pm.outputs.node-cache }}
        CACHE-HIT: ${{ steps.node-modules-cache.outputs.cache-hit }}

    - name: Display Node.js and Package Manager versions
      run: |
        echo
        VERSION=$(
          case "$PM" in
            yarn1|yarn) yarn -v ;;
            pnpm) pnpm -v ;;
            *) npm -v ;;
          esac
        )
        echo "📦 Node.js version: $(node -v)"
        echo "📦 $PM version: $VERSION"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        PM: ${{ steps.detect-node-pm.outputs.node-pm }}

    - name: Install Dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: |
        echo
        echo "::group::📦 Installing dependencies"
        case "$PM" in
          yarn1) yarn install --frozen-lockfile ;;
          yarn) yarn --immutable ;;
          pnpm) pnpm install --frozen-lockfile ;;
          *) npm ci ;;
        esac
        echo "::endgroup::"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        PM: ${{ steps.detect-node-pm.outputs.node-pm }}

    - name: Calculate dependencies size
      run: |
        echo
        echo 📦⚖️ Calculating dependencies size

        find . -path "*/node_modules" -type d -prune -print | \
        xargs -r du -sm | \
        sort -nr | \
        while read -r size path; do
          printf "\033[1;35m %4sM \033[0m %s\n" "$size" "$path"
        done
      shell: bash
      working-directory: ${{ inputs.working-directory }}
