name: Setup Python
description: Setups latest Python and installs dependencies

runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        check-latest: true
        python-version: 3

    - name: Display Python version
      run: python -V
      shell: bash

    - name: Display Pip version
      run: pip -V
      shell: bash

    - name: Install Python Dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
      shell: bash
