---
name: Setup Python
description: Setups latest Python and installs dependencies

inputs:
  python-version:
    description: Python version to install
    default: '3'
  working-directory:
    description: Action working directory
    default: .

runs:
  using: composite
  steps:
    - name: Load Cached Python dependencies
      uses: actions/cache@v4
      id: python-cache
      with:
        path: .venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/*requirements.txt','**/*requirements-dev.txt') }}

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        cache: ${{ env.CACHE-HIT != 'true' && 'pip' || env.NOTDEFINED }}
        check-latest: true
        python-version: ${{ inputs.python-version }}
        cache-dependency-path: |
          **/pyproject.toml
          **/requirements.txt
          **/requirements-dev.txt
      env:
        CACHE-HIT: ${{ steps.python-cache.outputs.cache-hit }}

    - name: Display Python version
      run: python -V
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Display Pip version
      run: pip -V
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Activate Python Virtual Env
      # Enables venv and stores its path for follow-up steps
      run: |
        python -m venv .venv
        . .venv/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Install Python Dependencies
      if: steps.python-cache.outputs.cache-hit != 'true'
      run: |
        python -m venv .venv
        . .venv/bin/activate
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
        fi
        if [ -f "requirements-dev.txt" ]; then
          pip install -r requirements-dev.txt
        fi
      shell: bash
      working-directory: ${{ inputs.working-directory }}
