name: Setup Python
description: Setups latest Python and installs dependencies

runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        check-latest: true
        python-version: 3
