---
name: Setup Python
description: Setups latest Python and installs dependencies

inputs:
  python-version:
    description: Python version to install
    default: '3'
  venv-dir:
    description: Directory for Python Virtual Env
    default: .venv
  working-directory:
    description: Action working directory
    default: .

runs:
  using: composite
  steps:
    - name: Load Cached Python dependencies
      uses: actions/cache@v4
      id: python-cache
      with:
        path: ${{ inputs.working-directory }}/${{ inputs.venv-dir }}
        key: ${{ env.CACHE-PREFIX }}-${{ hashFiles(env.HASHED1, env.HASHED2) }}
      env:
        CACHE-PREFIX: setup-python-internal-${{ runner.os }}-${{ runner.arch }}-venv
        HASHED1: ${{ inputs.working-directory }}/**/*requirements.txt
        HASHED2: ${{ inputs.working-directory }}/**/requirements-dev.txt

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        # Reference for setup-python action options
        # https://github.com/actions/setup-python/blob/main/action.yml
        # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md
        cache: ${{ env.CACHE-HIT != 'true' && 'pip' || env.NOTDEFINED }}
        check-latest: true
        python-version: ${{ inputs.python-version }}
        cache-dependency-path: |
          **/pyproject.toml
          **/requirements.txt
          **/requirements-dev.txt
      env:
        CACHE-HIT: ${{ steps.python-cache.outputs.cache-hit }}

    - name: Display Python and Pip versions
      run: |
        echo
        echo 🐍 Python version: $(python -V)
        echo 🐍 Pip version: $(pip -V)
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Create Python Virtual Env
      run: |
        echo
        if [ ! -d "${{ inputs.venv-dir }}" ]; then
          echo "🐍 Creating Python Virtual Env"
          python -m venv ${{ inputs.venv-dir }}
        fi

        VENV_PATH="${{ inputs.working-directory }}/${{ inputs.venv-dir }}/bin"
        echo "🐍 Adding Python Virtual Env $VENV_PATH to PATH"
        echo "$VENV_PATH" >> $GITHUB_PATH
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Install Python Dependencies
      if: steps.python-cache.outputs.cache-hit != 'true'
      run: |
        echo
        echo "🐍 Activating Python Virtual Env"
        . ${{ inputs.venv-dir }}/bin/activate

        if [ -f "requirements.txt" ]; then
          echo "::group::🐍 Installing dependencies"
          pip install -r requirements.txt
          echo "::endgroup::"
        fi
        if [ -f "requirements-dev.txt" ]; then
          echo "::group::🐍 Installing dev dependencies"
          pip install -r requirements-dev.txt
          echo "::endgroup::"
        fi
      shell: bash
      working-directory: ${{ inputs.working-directory }}
