---
name: Setup Python
description: Setups latest Python and installs dependencies

inputs:
  python-version:
    description: 'Python version to install'
    default: '3'

runs:
  using: composite
  steps:
    - name: Load Cached Python dependencies
      uses: actions/cache@v4
      id: python-cache
      with:
        path: .venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/*requirements.txt') }}

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        cache: ${{ env.CACHE-HIT != 'true' && 'pip' || env.NOTDEFINED }}
        check-latest: true
        python-version: ${{ inputs.python-version }}
      env:
        CACHE-HIT: ${{ steps.python-cache.outputs.cache-hit }}

    - name: Display Python version
      run: python -V
      shell: bash

    - name: Display Pip version
      run: pip -V
      shell: bash

    - name: Activate Python Virtual Env
      # Enables venv and stores its path for follow-up steps
      run: |
        python -m venv .venv
        . .venv/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV
      shell: bash

    - name: Install Python Dependencies
      if: steps.python-cache.outputs.cache-hit != 'true'
      run: |
        python -m venv .venv
        . .venv/bin/activate
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
        fi
        if [ -f "requirements-dev.txt" ]; then
          pip install -r requirements-dev.txt
        fi
      shell: bash
