---
name: Setup Python
description: Setups latest Python and installs dependencies

inputs:
  python-version:
    description: Python version to install
    default: '3'
  venv-dir:
    description: Directory for Python Virtual Env
    default: .venv
  working-directory:
    description: Action working directory
    default: .

outputs:
  python-version:
    description: Installed Python version
    value: ${{ steps.display-installed-versions.outputs.node-version }}
  package-manager-version:
    description: Installed Python Package Manager version
    value: ${{ steps.display-installed-versions.outputs.package-manager-version }}

runs:
  using: composite
  steps:
    - name: Detect Python version
      id: detect-python-version
      run: |
        echo
        echo "📄 Detecting Python version controlled by file"

        if [ -f ".python-version" ]; then
          VERSION=$(cat .python-version)
          echo "📄 Detected .python-version file"
        else
          VERSION="${{ inputs.python-version }}"
          echo "📄 No .python-version detected"
        fi

        echo "🐍 Detected Python version: $VERSION"
        echo "python-version=$VERSION" >> "$GITHUB_OUTPUT"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Detect Cache type
      id: detect-cache-type
      run: |
        echo
        echo "💾 Detecting Python cache type"
        if [ -f Pipfile.lock ]; then
          CACHE_TYPE=pipenv
          CACHE_PATH="${{ inputs.working-directory }}/**/poetry.lock"
        elif [ -f poetry.lock ] || grep -q '\[tool.poetry\]' pyproject.toml 2>/dev/null; then
          CACHE_TYPE=poetry
          CACHE_PATH="${{ inputs.working-directory }}/**/Pipfile.lock"
        else
          CACHE_TYPE=pip
          CACHE_PATH="${{ inputs.working-directory }}/**/*requirements{,-dev}.txt"
        fi

        echo "💾 Detected Python cache type: $CACHE_TYPE"
        echo "cache-type=$CACHE_TYPE" >> "$GITHUB_OUTPUT"
        echo "cache-path=$CACHE_PATH" >> "$GITHUB_OUTPUT"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Load Cached Python dependencies
      uses: actions/cache@v4
      id: python-cache
      with:
        path: ${{ inputs.working-directory }}/${{ inputs.venv-dir }}
        key: ${{ env.CACHE-PREFIX }}-${{ hashFiles(env.HASH) }}
      env:
        CACHE-PREFIX: setup-python-internal-${{ runner.os }}-${{ runner.arch }}-venv
        HASH: ${{ hashFiles(steps.detect-cache-type.outputs.cache-path) }}

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        # Reference for setup-python action options
        # https://github.com/actions/setup-python/blob/main/action.yml
        # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md
        cache: ${{ env.CACHE_HIT == 'true' && '' || env.CACHE_TYPE }}
        check-latest: true
        python-version: ${{ steps.detect-python-version.outputs.python-version }}
        cache-dependency-path: ${{ env.CACHE_PATH }}
      env:
        CACHE_HIT: ${{ steps.python-cache.outputs.cache-hit }}
        CACHE_PATH: ${{ steps.detect-cache-type.outputs.cache-path }}
        CACHE_TYPE: ${{ steps.detect-cache-type.outputs.cache-type }}

    - name: Display installed Python and Pip versions
      id: display-installed-versions
      run: |
        echo
        PYTHON_VERSION=$(python -V)
        PM_VERSION=$(pip -V)
        echo "python-version=$PYTHON_VERSION" >> $GITHUB_OUTPUT
        echo "package-manager-version=$PM_VERSION" >> $GITHUB_OUTPUT
        echo "🐍 Python version: $PYTHON_VERSION"
        echo "🐍 Pip version: $PM_VERSION"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Create Python Virtual Env
      run: |
        echo
        if [ ! -d "${{ inputs.venv-dir }}" ]; then
          echo "🐍 Creating Python Virtual Env"
          python -m venv ${{ inputs.venv-dir }}
        fi

        VENV_PATH="$(realpath "${{ inputs.venv-dir }}/bin")"
        echo "🐍 Adding Python Virtual Env $VENV_PATH to PATH"
        echo "$VENV_PATH" >> $GITHUB_PATH
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Install Python Dependencies
      if: steps.python-cache.outputs.cache-hit != 'true'
      run: |
        echo
        echo "🐍 Activating Python Virtual Env"
        . ${{ inputs.venv-dir }}/bin/activate

        if [ -f "requirements.txt" ]; then
          echo "::group::🐍 Installing dependencies"
          pip install -r requirements.txt
          echo "::endgroup::"
        fi
        if [ -f "requirements-dev.txt" ]; then
          echo "::group::🐍 Installing dev dependencies"
          pip install -r requirements-dev.txt
          echo "::endgroup::"
        fi
      shell: bash
      working-directory: ${{ inputs.working-directory }}
