---
name: PR
# yamllint disable-line rule:truthy
on: pull_request_target

jobs:
  auto-review:
    name: Auto review
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Auto Review
        uses: ./auto-review

  pr-conventional-commits:
    name: Check Conventional Commit in PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Conventional Commit in PR
        uses: ./pr-conventional-commits
