---
name: tests
# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
  pull_request: {}

permissions: read-all

jobs:
  test-setup-node-npm:
    name: Node with npm
    uses: ./.github/workflows/test-setup-node.yml
    with:
      working-directory: ./test/setup-node/npm
    permissions:
      actions: write

  test-setup-node-pnpm:
    name: Node with pnpm
    uses: ./.github/workflows/test-setup-node.yml
    with:
      working-directory: ./test/setup-node/pnpm
    permissions:
      actions: write

  test-setup-node-yarn1:
    name: Node with yarn1
    uses: ./.github/workflows/test-setup-node.yml
    with:
      working-directory: ./test/setup-node/yarn1
    permissions:
      actions: write

  test-setup-node-yarn:
    name: Node with yarn
    uses: ./.github/workflows/test-setup-node.yml
    with:
      working-directory: ./test/setup-node/yarn
    permissions:
      actions: write

  test-setup-python-pip:
    name: Python with pip
    uses: ./.github/workflows/test-setup-python.yml
    with:
      working-directory: ./test/setup-python/pip
    permissions:
      actions: write

  test-setup-python-pipenv:
    name: Python with pipenv
    uses: ./.github/workflows/test-setup-python.yml
    with:
      working-directory: ./test/setup-python/pipenv
    permissions:
      actions: write

  test-setup-python-poetry:
    name: Python with poetry
    uses: ./.github/workflows/test-setup-python.yml
    with:
      working-directory: ./test/setup-python/poetry
    permissions:
      actions: write

  test-setup-ansible:
    name: Test Setup Ansible
    uses: ./.github/workflows/test-setup-ansible.yml
    with:
      working-directory: ./test/setup-ansible
    permissions:
      actions: write
